spring:
  application:
    name: dcs
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:33067/dcs
    username: root
    password: test1234

mybatis:
  mapper-locations: classpath:mappers/*.xml
  config-location: classpath:mappers/config/configuration.xml

