spring:
  application:
    name: dcs
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:33067/dcs
    username: root
    password: 1234
  mail:
    host: smtp.gmail.com
    port: 587
    username: gyust941326@gmail.com
    password: pantppqokveizzpo
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
mybatis:
  mapper-locations: classpath:mappers/*.xml
  config-location: classpath:mappers/config/configuration.xml

